name: dash-fw

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  dash-fw-windows:
    strategy:
        matrix:
          display: [ JC8048W550C, WAVESHARE_S3_LCD7, WAVESHARE_S3_LCD5 ]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli lib install lvgl@8.4.0
          arduino-cli lib install LovyanGFX@1.2.0
          arduino-cli lib install ESP32_IO_Expander@1.1.0
          arduino-cli core install esp32:esp32

      - name: Compile Sketch
        working-directory: firmware
        run: |
          echo "#define ${{matrix.display}}" >> config.h
          arduino-cli compile -b esp32:esp32:esp32s3:UploadSpeed=115200,FlashSize=16M,PartitionScheme=app3M_fat9M_16MB,PSRAM=opi --build-property compiler.cpp.extra_flag=-D${{matrix.display}} --build-property compiler.cpp.extra_flag=-O2 --build-property compiler.c.extra_flags=-O2 firmware.ino -e -v